### ISSUE TITLE
"Missed Schedule" Improvement 

### ISSUE THREAD

**Issue by khan-rafin-ahmed** [WPDevelopers/wp-scheduled-posts#50]
1. There should be a toggle turn on or off option for Missed Schedule just like Auto & Manual Scheduler. 

2. "Activated Missed Schedule" color should be more visible. 

3. After "Missed Schedule" is activated, the button doesn't change to "Deactivate". 

Here's the GIF file for demonstrating the issue:

![wpsp-missed-schedule](https://user-images.githubusercontent.com/42029211/50267622-10f79080-0452-11e9-993a-c2a6fb01f503.gif)

**Comment by Asif2BD** [comment]
@hakimcseru , let's bring this, seems like a good idea.
