### ISSUE TITLE
Scheduled Posts not showing in Calendar view WP 5.3

### ISSUE THREAD

**Issue by stevenfeldman** [WPDevelopers/wp-scheduled-posts#81]
I have just upgraded my WP install to 5.3 and Scheduled Posts to 3.12

None of my scheduled posts are showing in the calendar view, is there a setting I need to adjust?

**Comment by IftekharPial** [comment]
Hello there,

Sorry for the late replay

Please update to the latest version of SchedulePress( Formally Scheduled Posts) to 4.1.5.
Hopefully, your issue will be solved.

Please let us know how it goes.

Thank you
