### ISSUE TITLE
Calendar Not Working. Eventually Causes Tab to Crash!

### ISSUE THREAD

**Issue by MuslimHS** [WPDevelopers/wp-scheduled-posts#82]
Hi, I'm currently running the latest version of all software in my setup including WP, WP Scheduled Posts Plugin and even my web browsers are up to date. For some reason ever since the last major update of this plugin I cannot access the Calendar Page successfully. Sometimes it load the calendar but the tab remains not responding and eventually the tab crashes while CPU usage jumps to really high. I'm wondering is this just happening on my setup or can you re-produce this? Please check into this ASAP. Thank you.

![Untitled-1](https://user-images.githubusercontent.com/26230641/69247773-93964c00-0bdd-11ea-98d9-374577b9561e.jpg)

**Comment by imrantushar** [comment]
Hello @MuslimHS
we are already fix this issue in development version. please wait 2/3 days for get final version. if you want to test development version please get latest file from "tushar-bugfix" branch
i hope your problem will be solve. otherwise please let me know

Thank You
