### ISSUE TITLE
Moving posts to a different day frequently resets the publish time to the default

### ISSUE THREAD

**Issue by mobilene** [WPDevelopers/wp-scheduled-posts#86]
Frequently, but not always, when I move a post to a different day, the time reverts to the Calendar Default Schedule Time. I would expect it to retain whatever time was already set on the post.

I'm working around this by setting Calendar Default Schedule Time to 5:00 am, as that's the time I have most of my posts publish anyway.

**Comment by rasel-wp** [comment]
Hi @mobilene,

Sorry for the late response.
This issue has been fixed already. If still, you have the issue please recheck once with the latest version of SchedulePress. It will be fixed.

Thanks!
