### ISSUE TITLE
DIVI Theme 

### ISSUE THREAD

**Issue by agenciaimma** [WPDevelopers/wp-scheduled-posts#89]
When I try to change my settings, all pages are completly blank. Nothing shows up.
I use DIVI.

**Comment by rasel-wp** [comment]
Hi @agenciaimma,

Sorry for the inconvenience caused. Please, create a support ticket through this link with details: https://wpdeveloper.net/support/new-ticket/.
Our support team will check your issue and get back to you very soon.

Thanks for your patience!

**Comment by rasel-wp** [comment]
Hi @agenciaimma,

This issue has been fixed already. If still, you have the issue please recheck once with the latest version of SchedulePress. It will be fixed.

Thanks!
