### ISSUE TITLE
When system generate token for Facebook share, everythings gone.

### ISSUE THREAD

**Issue by strega07** [WPDevelopers/wp-scheduled-posts#90]
I started to use this plugin. I get my facebook app ID and secret and provide them to plugin. it says generate token then freeze. Now the settings menu tabs not show. Tab header showns but details of setting not showing. I delete plugin then install again. its same
![press](https://user-images.githubusercontent.com/79356561/108628414-cc217700-746b-11eb-9baa-9c2456328e31.png)

**Comment by rasel-wp** [comment]
Hi @strega07,

Sorry for the inconvenience caused.
It seems to a plugin conflict issue. Please, do a plugin conflict test. You can check for Plugin conflicts by deactivating all the third-party plugins one by one except for **SchedulePress & SchedulePress Pro**. Simply go to your WordPress Dashboard and navigate to wp-admin -> Plugins and then, deactivate other Plugins.

If still, you are facing the same issue please, create a support ticket through this link with details: https://wpdeveloper.net/support/new-ticket/.
Our support team will check your issue and get back to you very soon.

Thanks for your patience!

**Comment by rasel-wp** [comment]
Hi @strega07,

This issue has been fixed already. If still, you have the issue please recheck once with the latest version of SchedulePress. It will be fixed.

Thanks!
