### ISSUE TITLE
Issue in Pinterest Account

### ISSUE THREAD

**Issue by ktasaddaq** [WPDevelopers/wp-scheduled-posts#92]
Hello Sir, i cannot add my Pinterest API in wp scheduled posts , it shows an error. how can connect my Pinterest account for autoposting.
error is 
{"status":"failure","code":11,"data":null,"message":"API method not found.","endpoint_name":null}
please help me to connect this.

**Comment by arrasel13** [comment]
Hi @ktasaddaq,

Sorry for the inconvenience caused. Yes we are aware of this issue. We have already fixed this issue on our Dev version plugin. And that version is on testing stage. Hopefully we will add this fixation on our next release.

For now, please download this Dev version plugin from here: https://d.pr/f/0YMU1g and check once.

Hope you understand. Thanks!

**Comment by ktasaddaq** [comment]
yes sir i setup plugin on  wordpress but still posts not updating on pinterst.

**Comment by arrasel13** [comment]
Hi @ktasaddaq 

Sorry for the inconvenience caused. Can you please inform me that did you update your plugin to the latest version (not the shared Dev version plugin) on your site? If you are using the latest version plugin, please reconnect your Pinterest account and try to share once.

And please inform me that you are getting error messages when sharing posts on Pinterest. If yes, please share a screenshot of that error message.

Let me know the update. Thanks!

**Comment by arrasel13** [comment]
Hi @ktasaddaq 

We have already fixed the Pinterest issue on our plugin. Please use the latest version plugin and retry. Your issue will be fixed.

Thanks!
