### ISSUE TITLE
Unscheduled posts no longer appearing in Unscheduled Posts list

### ISSUE THREAD

**Issue by mobilene** [WPDevelopers/wp-scheduled-posts#95]
Until recently, the Unscheduled Posts section of the Calendar page showed all of my draft posts. Now it does not. This link is a video showing that I have four draft posts, but none of them appear in Unscheduled Posts. Could draft posts please again be shown in Unscheduled Posts?

https://screencast-o-matic.com/watch/c3lnYwVUSTz

**Comment by arrasel13** [comment]
Hi @mobilene,

Sorry for the inconvenience caused. We already fixed this issue on our Dev version plugin. Please download the Dev version plugin from here: https://d.pr/f/8oRgNn and check with this. Hope your issue will be fixed.

Let us know if you are facing any issues.

Thanks!

**Comment by mobilene** [comment]
Thanks for the response! I'll check out the dev version. Assume all is well unless you hear from me again!
